# Generated by Django 4.2.1 on 2023-05-18 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc_title", models.CharField(max_length=150)),
                ("disc_creation_data", models.DateField(auto_now_add=True)),
                (
                    "disc_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discussion",
                "verbose_name_plural": "Discussions",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=100)),
                (
                    "section_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "section_logo",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
            options={"verbose_name": "Section", "verbose_name_plural": "Sections",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_content", models.TextField()),
                ("post_creation_data", models.DateField(auto_now_add=True)),
                (
                    "post_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.discussion",
                    ),
                ),
            ],
            options={"verbose_name": "Post", "verbose_name_plural": "Posts",},
        ),
        migrations.AddField(
            model_name="discussion",
            name="disc_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="forum.section"
            ),
        ),
    ]
